<?PHP


//////////////////////////////////////////////////


//              PROPRIETE STATIC
//
//
// public static methode/propriete
//
//
// la methode peut etre appeleer direct sur la classe
//
//  HORS STATIC : 
//
//  $form = new Form();
//  echo $form->checkbox('demo', 'demo', []);
//
//
// STATIC : 
//
// NOM CLASSE :: METHODE
//      ex : echo Form::checkbox('demo', 'demo', []);
//
// NOM CLASSE :: $ PROPRIETE
//      ex : echo Form::$class;
