<?PHP

//                      CLASS


// defini le fonctionement d un systeme

// vulgairement THIS == L OBJET CREE
// dessous $this == perso
//
//  ex:     $perso = new xxx('akro');
//
//
//  class xxx 
//      {
//         public $nom;
//
//         public function __construct($name)
//         {
//               $this->nom=$name;
//         }
//      }



// TYPAGE :
//
// donne un nom a l objet
//
// ex : ici Creaneau
// public function intersect(Creneau $creneau): bool
